spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 81577215z
    url: jdbc:mysql://localhost:3306/carbon_emission?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC